server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smytest?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    http:
      encoding:
          force: true
          charset: UTF-8
          enabled: true
